name = "bbs_ansiterm"
description = "Generate Escape Sequences for ANSI terminals"
version = "0.1.0"

long-description="""
Constants, functions, and procedures for generating ANSI escape sequences.
Refer to the documentation for more information.
"""

authors = ["Brent Seidel"]
maintainers = ["Brent Seidel <brentseidel@mac.com>"]
maintainers-logins = ["BrentSeidel"]
licenses = "GPL-3.0-or-later"
website = ""
tags = ["vt100", "escape", "ansi"]

[[depends-on]]
bbs = "~0.1.0"
